# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e59c96f657804a34c463e646c6323b39acbf3ff5839b3bb914ebe429b22d6fb65c6952eb038fcec68b41a91b2eb27a87ea80034462910b218ee82d7d990d93

test:
  secret_key_base: f1e6574b857d9d5b35a4a9b6bcb2cedba3492d227178d3629ade55eca23a8a8ee5592fb877e5d4cb4edfd38fc46f4a2f26f899ce12efea446bbb9cb0db420bb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
